package it.maggioli.eldasoft.sil.gare.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2016-09-01T16:31:15.037+02:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "WSGareAppalto", 
                  wsdlLocation = "http://localhost:8100/WSAppalti/services/WSGareAppaltoSOAP?wsdl",
                  targetNamespace = "http://www.eldasoft.it/sil/WSGareAppalto/") 
public class WSGareAppalto extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.eldasoft.it/sil/WSGareAppalto/", "WSGareAppalto");
    public final static QName WSGareAppaltoSOAP = new QName("http://www.eldasoft.it/sil/WSGareAppalto/", "WSGareAppaltoSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8100/WSAppalti/services/WSGareAppaltoSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSGareAppalto.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8100/WSAppalti/services/WSGareAppaltoSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSGareAppalto(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSGareAppalto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGareAppalto() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WSGareAppaltoSoap
     */
    @WebEndpoint(name = "WSGareAppaltoSOAP")
    public WSGareAppaltoSoap getWSGareAppaltoSOAP() {
        return super.getPort(WSGareAppaltoSOAP, WSGareAppaltoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSGareAppaltoSoap
     */
    @WebEndpoint(name = "WSGareAppaltoSOAP")
    public WSGareAppaltoSoap getWSGareAppaltoSOAP(WebServiceFeature... features) {
        return super.getPort(WSGareAppaltoSOAP, WSGareAppaltoSoap.class, features);
    }

}
