package it.maggioli.eldasoft.sil.gare.ws;

import it.maggioli.eldasoft.sil.gare.ws.search.AvvisiTypeSearch;
import it.maggioli.eldasoft.sil.gare.ws.search.EsitoTypeSearch;
import it.maggioli.eldasoft.sil.gare.ws.search.GaraTypeSearch;
import org.apache.cxf.annotations.WSDLDocumentation;

import javax.jws.WebParam;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-01T16:31:15.037+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService( 
			targetNamespace = "http://www.eldasoft.it/sil/WSGareAppalto/",  
			name = "WSGareAppaltoSoap" )
public interface WSGareAppaltoSoap {
	
	/**
	 * NB: aggiungere ai metodi l'annotazione per la documentazione
	 * 
	 *     @WSDLDocumentation("..........")
	 * 
	 */
	
	@WSDLDocumentation("Restituisce  la versione del servizio.")
	public it.maggioli.eldasoft.sil.gare.ws.VersionOutType getVersion();
		
	@WSDLDocumentation("Restituisce la versione della webapp 'Appalti'.")
	public it.maggioli.eldasoft.sil.gare.ws.VersionOutType getAppaltiVersion();
	
	@WSDLDocumentation("Estrae i dati attribuiti alla creazione del fascicolo.")
    public it.maggioli.eldasoft.sil.gare.ws.GetFascicoloProtocolloOutType getFascicoloProtocollo(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Restituisce l'elenco dei tipi di impresa/consorzio")
    public java.lang.String getElencoTipiImpresaConsorzio();

	@WSDLDocumentation("Restituisce l'elenco delle unita&agrave; di misura per i tempi di consegna.")
    public java.lang.String getElencoUnitaMisuraTempoConsegna();

	@WSDLDocumentation("Restituisce le comunicazioni inviate da un utente per una eventuale entit&agrave;.")
    public it.maggioli.eldasoft.sil.gare.ws.ComunicazioniPersonaliOutType getComunicazioniPersonaliInviate(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "codice2", targetNamespace = "")
        java.lang.String codice2,
        @WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
        int indicePrimoRecord,
        @WebParam(name = "maxNumRecord", targetNamespace = "")
        int maxNumRecord,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
        java.lang.String stazioneAppaltante
    );

	@WSDLDocumentation("Restituisce lìelenco dei tipi di impresa per l'iscrizione.")
    public java.lang.String getElencoTipiImpresaPerIscrizione();

	@WSDLDocumentation("Ritorna l'elenco dei bandi di gara in corso di validit&agrave;")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType getElencoBandi(
            @WebParam(name = "filtri", targetNamespace = "")
            GaraTypeSearch filtri
    );
	
	@WSDLDocumentation("Ritorna l'elenco dei bandi di gara in corso di validit&agrave; per gare privatistiche")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType getElencoBandiPrivatistiche(
            @WebParam(name = "filtri", targetNamespace = "")
            GaraTypeSearch filtri
    );

	@WSDLDocumentation("Restituisce l'elenco delle classificazioni per le forniture.")
    public java.lang.String getElencoClassificazioniForniture();

	@WSDLDocumentation("Restituisce l'elenco delle calssificazioni dei servizi professionali.")
    public java.lang.String getElencoClassificazioniServiziProfessionali();

	@WSDLDocumentation("Restituisce l'elenco dei tipi di articolo.")    
	public java.lang.String getElencoTipiArticolo();

	@WSDLDocumentation("Ritorna l'elenco degli avvisi di gara in corso di validit&agrave;.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoAvvisiOutType getElencoAvvisi(
            @WebParam(name = "filtri", targetNamespace = "")
            AvvisiTypeSearch filtri
    );

	@WSDLDocumentation("Restituisce l'elenco delle categorie dei tipi di appalto.")
    public java.lang.String getElencoTipiAppaltoCategorie();

	@WSDLDocumentation("Estrae lo stato di un'eventuale iscrizione all'elenco fornitori in input per l'impresa")
    public it.maggioli.eldasoft.sil.gare.ws.StatoIscrizioneABandoIscrizioneOutType getStatoIscrizioneABandoIscrizione(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );
 
	@WSDLDocumentation("Restituisce le comunicazioni ricevute ed archiviate (cio&egrave; ricevute " + 
					   "oltre 90 giorni fa) da un utente per una gara a lotti.")
    public it.maggioli.eldasoft.sil.gare.ws.ComunicazioniPersonaliOutType getComunicazioniPersonaliArchiviateGaraLotti(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
        @WebParam(name = "soccorsoIstruttorio", targetNamespace = "")
        java.lang.Boolean soccorsoIstruttorio,
        @WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
        int indicePrimoRecord,
        @WebParam(name = "maxNumRecord", targetNamespace = "")
        int maxNumRecord,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
        java.lang.String stazioneAppaltante
    );
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di classifica.")
    public java.lang.String getElencoTipiClassifica();

	@WSDLDocumentation("Restituisce l'elenco delle stazioni appaltanti associate ad un bando d'iscrizione")
    public java.lang.String getElencoStazioniAppaltantiPerIscrizione(
        @WebParam(name = "codiceBandoIscrizione", targetNamespace = "")
        java.lang.String codiceBandoIscrizione
    );

	@WSDLDocumentation("Restituisce l'elenco delle classificazioni dei lavori.")
    public java.lang.String getElencoClassificazioniLavori();

	@WSDLDocumentation("Ritorna l'elenco dei prodotti filtrati in base ai parametri in input.")
    public it.maggioli.eldasoft.sil.gare.ws.SearchProdottiOutType searchProdotti(
        @WebParam(name = "codiceCatalogo", targetNamespace = "")
        java.lang.String codiceCatalogo,
        @WebParam(name = "idArticolo", targetNamespace = "")
        java.lang.Long idArticolo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "terminiRicerca", targetNamespace = "")
        java.lang.String terminiRicerca,
        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
        int indicePrimoRecord,
        @WebParam(name = "maxNumRecord", targetNamespace = "")
        int maxNumRecord
    );

	@WSDLDocumentation("Testa se le consorziate esecutrici di un consorzio sono gi&agrave; presenti in backoffice.")
	public it.maggioli.eldasoft.sil.gare.ws.EsitoOutType isConsorziateEsecutriciPresenti(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Restituisce l'elenco delle categorie per cui un'impresa risulta iscritta ad un albo.")
    public it.maggioli.eldasoft.sil.gare.ws.CategorieImpresaPerIscrizioneOutType getCategorieImpresaPerIscrizione(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Restituisce i dati generali per cui un'impresa risulta iscritta ad un albo.")
    public it.maggioli.eldasoft.sil.gare.ws.ImpresaIscrizioneOutType getImpresaIscrizione(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di elenco degli operatori.")
    public java.lang.String getElencoTipiElencoOperatori();

	@WSDLDocumentation("Restituisce le comunicazioni ricevute ed archiviate (cio&egrave; ricevute " + 
	   				   "oltre 90 giorni fa) da un utente per una eventuale entit&agrave;.")
	public it.maggioli.eldasoft.sil.gare.ws.ComunicazioniPersonaliOutType getComunicazioniPersonaliArchiviate(
		@WebParam(name = "tokenRichiedente", targetNamespace = "")
		java.lang.String tokenRichiedente,
		@WebParam(name = "codice", targetNamespace = "")
		java.lang.String codice,
		@WebParam(name = "codice2", targetNamespace = "")
		java.lang.String codice2,
		@WebParam(name = "soccorsoIstruttorio", targetNamespace = "")
		java.lang.Boolean soccorsoIstruttorio,
		@WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
		@WebParam(name = "indicePrimoRecord", targetNamespace = "")
		int indicePrimoRecord,
		@WebParam(name = "maxNumRecord", targetNamespace = "")
		int maxNumRecord,
		@WebParam(name = "stazioneAppaltante", targetNamespace = "")
		java.lang.String stazioneAppaltante
	);

	@WSDLDocumentation("Restituisce la lista degli esiti filtrando per i parametri di input.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoEsitiOutType searchEsiti(
        @WebParam(name = "filtri", targetNamespace = "")
        EsitoTypeSearch filtri
    );

	@WSDLDocumentation("Estrae la lista delle voci di dettaglio presenti in una lista lavorazioni " +
				       "che non sono oggetto di ribasso nell'offerta telematica.")
    public it.maggioli.eldasoft.sil.gare.ws.GetVociDettaglioOffertaOutType getVociDettaglioOffertaNoRibasso(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Estrae l'elenco dei documenti richiesti all'atto del rinnovo iscrizione all'albo " +
					   "elenco operatori economici dipendenti anche dalla tipologia d'impresa.")
    public it.maggioli.eldasoft.sil.gare.ws.GetDocumentiRichiestiBandoOutType getDocumentiRichiestiRinnovoIscrizione(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "tipoImpresa", targetNamespace = "")
        java.lang.String tipoImpresa,
        @WebParam(name = "rti", targetNamespace = "")
        boolean rti
    );
	
	@WSDLDocumentation("Estrae l'elenco dei documenti richiesti di una comunicazione.")
	public GetDocumentiRichiestiBandoOutType getDocumentiRichiestiComunicazione(
		@WebParam(name = "idPrg", targetNamespace = "")
		java.lang.String idPrg, 
		@WebParam(name = "idComunicazione", targetNamespace = "")
		long idComunicazione 
	); 

	@WSDLDocumentation("Restituisce l'elenco dei tipi di prezzo per gli articoli.")
    public java.lang.String getElencoTipiPrezzoArticoloRiferitoA();

	@WSDLDocumentation("Ritorna i dati di dettaglio di una stazione appaltante.")
    public it.maggioli.eldasoft.sil.gare.ws.GetDettaglioStazioneAppaltanteOutType getDettaglioStazioneAppaltante(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );
	
	@WSDLDocumentation("Ritorna l'elenco delle stazioni appaltanti.")
	public it.maggioli.eldasoft.sil.gare.ws.GetStazioniAppaltantiOutType getStazioniAppaltanti();

	@WSDLDocumentation("Restituisce le statistiche delle comunicazioni ricevute e archiviate, " + 
			           "eventualmente da leggere, e quelle inviate, per una gara a lotti distinti.")
    public it.maggioli.eldasoft.sil.gare.ws.GetStatisticheComunicazioniPersonaliOutType getStatisticheComunicazioniPersonaliGaraLotti(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
        @WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
        java.lang.String stazioneAppaltante
    );	

	@WSDLDocumentation("Restituisce il dettaglio di una gara a partire dalla sua chiave")
    public it.maggioli.eldasoft.sil.gare.ws.DettaglioGaraOutType getDettaglioGara(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Restituisce l'elenco degli stati dei prodotti.")
    public java.lang.String getElencoStatiProdotto();

	@WSDLDocumentation("Restituisce il dettaglio di un avviso di gara a partire dalla sua chiave.")
    public it.maggioli.eldasoft.sil.gare.ws.DettaglioAvvisoOutType getDettaglioAvviso(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Restituisce il numero di prodotti inseriti in stato 'In catalogo' o 'In " +
					   "attesa di verifica' da parte dell'impresa in input su un determinato " +
					   "articolo in catalogo.")
    public it.maggioli.eldasoft.sil.gare.ws.RisultatoNumericoOutType getNumProdottiOEInArticolo(
        @WebParam(name = "idArticolo", targetNamespace = "")
        long idArticolo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

	@WSDLDocumentation("Restituisce l'elenco degli stati iscrizione dell'elenco operatori.")
    //    public GetElencoStatiIscrizioneElencoOperatoriResponse getElencoStatiIscrizioneElencoOperatori(
    //    L'aggiunta del parametro è comparsa dopo la conversione da axis a cxf
    //	  Il parametro non serve è per ora rimane commentato
    //	  Rimane da capire come si è comparso il parametro "parametes" nella firma   
    //	  A questo tipo di metodo non servono dei parametri
    //        @WebParam(partName = "parameters", name = "GetElencoStatiIscrizione", targetNamespace = "")
    //        GetElencoStatiIscrizione parameters);
 	public java.lang.String getElencoStatiIscrizioneElencoOperatori();

	@WSDLDocumentation("Estrae la chiave pubblica di cifratura busta se prevista")
    public it.maggioli.eldasoft.sil.gare.ws.RisultatoStringaOutType getChiavePubblica(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.String tipo
    );

	@WSDLDocumentation("Restituisce la lista dei bandi per procedure in aggiudicazione o concluse " +
					   "dell'impresa filtrando per i parametri di input.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType searchBandiPerProcInAggiudicazione(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce la lista dei bandi per procedure in aggiudicazione o concluse " +
	 	   			   "dell'impresa filtrando per i parametri di input per gare privatistiche.")
	public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType searchBandiPerProcInAggiudicazionePrivatistiche(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);
	
	@WSDLDocumentation("Restituisce la lista generale dei bandi per procedure " +
	   "filtrando per i parametri di input.")
	public ElencoBandiOutType searchBandiConEsito(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);	        
		
	@WSDLDocumentation("Estrae l'elenco dei documenti richiesti all'atto dell'iscrizione all'albo " +
					   "elenco operatori economici dipendenti anche dalla tipologia d'impresa")
	public it.maggioli.eldasoft.sil.gare.ws.GetDocumentiRichiestiBandoOutType getDocumentiRichiestiBandoIscrizione(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "tipoImpresa", targetNamespace = "")
        java.lang.String tipoImpresa,
        @WebParam(name = "rti", targetNamespace = "")
        boolean rti
    );

	@WSDLDocumentation("Restituisce, a partire da un catalogo e da una impresa, l'elenco delle "+
					   "categorie per cui un'impresa risulta iscritta al catalogo, e per ogni " +
					   "categoria ritorna i prodotti ad essa associati.<br/> " + 
					   "Vengono ritornate le sole categorie contenenti articoli, oppure categorie " + 
					   "aventi categorie figlie contenenti articoli.")
    public it.maggioli.eldasoft.sil.gare.ws.GetCategorieArticoliOEOutType getCategorieArticoliOE(
        @WebParam(name = "codiceCatalogo", targetNamespace = "")
        java.lang.String codiceCatalogo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

	@WSDLDocumentation("Estrae l'elenco delle abilitazioni di un'impresa ad un bando di gara.")
    public it.maggioli.eldasoft.sil.gare.ws.GetAbilitazioniGaraOutType getAbilitazioniGara(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Restituisce il dettaglio di un bando d'iscrizione a partire dalla sua chiave.")
	public it.maggioli.eldasoft.sil.gare.ws.DettaglioBandoIscrizioneOutType getDettaglioBandoIscrizione(
        @WebParam(name = "codiceBandoIscrizione", targetNamespace = "")
        java.lang.String codiceBandoIscrizione,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
	    java.lang.String stazioneAppaltante
	);
		
	@WSDLDocumentation("Restituisce la lista dei cataloghi filtrati dai parametri in input.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiIscrizioneOutType searchCataloghi(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "stato", targetNamespace = "")
        java.lang.Integer stato,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
	    java.lang.String stazioneAppaltante,
        @WebParam(name = "isAttivo", targetNamespace = "")
        java.lang.Boolean isAttivo
    );

	@WSDLDocumentation("Restituisce la lista dei bandi d'iscrizione.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiIscrizioneOutType getElencoBandiIscrizione(
    		@WebParam(name = "stazioneAppaltante", targetNamespace = "")
    		java.lang.String stazioneAppaltante
            , @WebParam(name = "isAttivo", targetNamespace = "")
            java.lang.Boolean isAttivo

    );
	
	@WSDLDocumentation("Ritorna l'elenco degli esiti di gara.")
	public ElencoEsitiOutType getElencoEsiti(
		@WebParam(name = "filtri", targetNamespace = "")
        EsitoTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce l'elenco delle stazioni appaltanti.")
    public java.lang.String getElencoStazioniAppaltanti();
	
	@WSDLDocumentation("Restituisce l'elenco delle stazioni appaltanti per la legge 190.")
    public java.lang.String getElencoStazioniAppaltantiL190();

	@WSDLDocumentation("Ritorna il genere di una procedura.")
    public it.maggioli.eldasoft.sil.gare.ws.RisultatoNumericoOutType getGenere(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Estrae la lista delle voci di dettaglio per l'inserimento dei " + 
			           "prezzi unitari nel caso di offerta telematica.")
    public it.maggioli.eldasoft.sil.gare.ws.GetVociDettaglioOffertaOutType getVociDettaglioOfferta(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Estrae l'elenco dei documenti richiesti all'atto dell'inserimento " + 
					   "di un invio offerta in una gara telematica a plico unico con offerte distinte. " + 
	 				   "La presente operazione estrae <b>TUTTI</b> i documenti richiesti " + 
	 				   "suddivisi per lotto e per busta.")
    public it.maggioli.eldasoft.sil.gare.ws.GetDocumentiRichiestiBandoOutType getDocumentiRichiestiBandoGara(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
        @WebParam(name = "codiceLotto", targetNamespace = "")
        java.lang.String codiceLotto,
        @WebParam(name = "tipoImpresa", targetNamespace = "")
        java.lang.String tipoImpresa,
        @WebParam(name = "rti", targetNamespace = "")
        boolean rti,
        @WebParam(name = "busta", targetNamespace = "")
        java.lang.String busta
    );

	@WSDLDocumentation("Restituisce l'elenco dei tipi impresa delle ditte individuale.")
    public java.lang.String getElencoTipiImpresaDittaIndividuale();

	//  18/11/2016 IL METODO NON E' PIU' UTILIZZATO
	//	@WSDLDocumentation("")
	//    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType getElencoBandiPerDomandePartecipazione(
	//        @WebParam(name = "tokenRichiedente", targetNamespace = "")
	//        java.lang.String tokenRichiedente
	//    );

	@WSDLDocumentation("Restituisce la lista dei bandi abilitati all'inserimento di richieste " + 
			           "di invio offerta per l'impresa in input")
	public ElencoBandiOutType getElencoBandiPerRichiesteOfferta(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce la lista dei bandi abilitati all'inserimento di richieste " + 
    				   "di invio offerta per l'impresa in input per gare privatistiche")
	public ElencoBandiOutType getElencoBandiPerRichiesteOffertaPrivatistiche(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce la lista dei bandi abilitati a delle aste elettroniche per l'impresa in input")
	public ElencoBandiOutType getElencoBandiPerAsteInCorso(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce il conteggio dei bandi abilitati a delle aste elettroniche per l'impresa in input")
	public ElencoBandiOutType countBandiPerAsteInCorso(
		@WebParam(name = "filtri", targetNamespace = "")
        GaraTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce l'elenco degli stati gara.")
    public java.lang.String getElencoStatiGara();
	
	@WSDLDocumentation("Restituisce l'elenco degli esiti gara.")
	public java.lang.String getElencoEsitiGara();

	@WSDLDocumentation("Ritorna l'elenco dei prodotti filtrati in base ai parametri in input.")
    public it.maggioli.eldasoft.sil.gare.ws.SearchProdottiOutType advancedSearchProdotti(
        @WebParam(name = "codiceCatalogo", targetNamespace = "")
        java.lang.String codiceCatalogo,
        @WebParam(name = "idArticolo", targetNamespace = "")
        java.lang.Long idArticolo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "tipoArticolo", targetNamespace = "")
        java.lang.String tipoArticolo,
        @WebParam(name = "descrizioneArticolo", targetNamespace = "")
        java.lang.String descrizioneArticolo,
        @WebParam(name = "coloreArticolo", targetNamespace = "")
        java.lang.String coloreArticolo,
        @WebParam(name = "codiceProdottoFornitore", targetNamespace = "")
        java.lang.String codiceProdottoFornitore,
        @WebParam(name = "nomeCommerciale", targetNamespace = "")
        java.lang.String nomeCommerciale,
        @WebParam(name = "descrizioneAggiuntiva", targetNamespace = "")
        java.lang.String descrizioneAggiuntiva,
        @WebParam(name = "statoProdotto", targetNamespace = "")
        java.lang.String statoProdotto,
        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
        int indicePrimoRecord,
        @WebParam(name = "maxNumRecord", targetNamespace = "")
        int maxNumRecord
    );

	@WSDLDocumentation("Ritorna l'elenco dei cataloghi in corso di validit&agrave;.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiIscrizioneOutType getElencoCataloghi(
    		@WebParam(name = "stazioneAppaltante", targetNamespace = "")
            java.lang.String stazioneAppaltante,
            @WebParam(name = "isAttivo", targetNamespace = "")
            java.lang.Boolean isAttivo
    );

	@WSDLDocumentation("Restituisce il dettaglio di un articolo a partire dalla sua chiave.")
    public it.maggioli.eldasoft.sil.gare.ws.GetArticoloOutType getArticolo(
    		@WebParam(name = "id", targetNamespace = "")
    		long id
    );

	@WSDLDocumentation("Ritorna l'elenco degli avvisi di gara scaduti.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoAvvisiOutType getElencoAvvisiScaduti(
            @WebParam(name = "filtri", targetNamespace = "")
            AvvisiTypeSearch filtri
	);

	@WSDLDocumentation("Fornisce l'indicazione se l'impresa in input risulta abilitata nel catalogo indicato.")
    public it.maggioli.eldasoft.sil.gare.ws.EsitoOutType isImpresaAbilitataCatalogo(
        @WebParam(name = "codiceCatalogo", targetNamespace = "")
        java.lang.String codiceCatalogo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

	@WSDLDocumentation("Restituisce il numero di prodotti inseriti in stato 'In catalogo' da parte " +
					   "di tutti gli altri operatori economici diversi dall'impresa in input.")
    public it.maggioli.eldasoft.sil.gare.ws.RisultatoNumericoOutType getNumProdottiAltriOEInArticolo(
        @WebParam(name = "idArticolo", targetNamespace = "")
        long idArticolo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

	@WSDLDocumentation("Restituisce la lista dei bandi filtrando per i parametri di input")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType searchBandi(
            @WebParam(name = "filtri", targetNamespace = "")
            GaraTypeSearch filtri
    );

	@WSDLDocumentation("Restituisce i lotti di una gara abilitati per un'impresa per la richiesta di offerta per una gara a lotti a plico unico con offerte distinte.")
    public it.maggioli.eldasoft.sil.gare.ws.LottiGaraOutType getLottiGaraPlicoUnicoPerRichiesteOfferta(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
		@WebParam(name = "progOfferta", targetNamespace = "")
		java.lang.String progOfferta

	);

	@WSDLDocumentation("Estrae l'elenco dei documenti richiesti all'atto dell'inserimento di un " +
			           "invio offerta in una gara telematica a plico unico con offerte distinte. " +
			           "La presente operazione estrae <b>TUTTI</b> i documenti richiesti suddivisi " + 
			           "per lotto e per busta.")    
	public it.maggioli.eldasoft.sil.gare.ws.GetDocumentiRichiestiBandoGaraPlicoUnicoOutType getDocumentiRichiestiBandoGaraPlicoUnico(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
        @WebParam(name = "tipoImpresa", targetNamespace = "")
        java.lang.String tipoImpresa,
        @WebParam(name = "rti", targetNamespace = "")
        boolean rti
    );

	@WSDLDocumentation("Restituisce la lista dei bandi d'iscrizione filtrati dai parametri in input")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiIscrizioneOutType searchBandiIscrizione(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "stato", targetNamespace = "")
        java.lang.Integer stato,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
        java.lang.String stazioneAppaltante,
        @WebParam(name = "isAttivo", targetNamespace = "")
        java.lang.Boolean isAttivo
    );

	@WSDLDocumentation("Fornisce l'indicazione se l'impresa in input risulta abilitata al rinnovo nel bando indicato.")
    public it.maggioli.eldasoft.sil.gare.ws.EsitoOutType isImpresaAbilitataRinnovo(
        @WebParam(name = "codiceBandoIscrizione", targetNamespace = "")
        java.lang.String codiceBandoIscrizione,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

	@WSDLDocumentation("")
    public it.maggioli.eldasoft.sil.gare.ws.GetAttiDocumentiBandoGaraOutType getAttiDocumentiBandoGara(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Ritorna il dettaglio di un contratto a partire dalla sua chiave.")
    public it.maggioli.eldasoft.sil.gare.ws.GetDettaglioContrattoOutType getDettaglioContratto(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Restituisce l'elenco dei tipi di aggiudicazione.")
    public java.lang.String getElencoTipiAggiudicazione();

	@WSDLDocumentation("Restituisce l'elenco delle classificazioni dei lavori sotto soglia.")    
	public java.lang.String getElencoClassificazioniLavoriSottoSoglia();

	@WSDLDocumentation("Restituisce i lotti di una gara abilitati per un'impresa per la richiesta di offerta")
    public it.maggioli.eldasoft.sil.gare.ws.LottiGaraOutType getLottiGaraPerRichiesteOfferta(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
		@WebParam(name = "progOfferta", targetNamespace = "")
		java.lang.String progOfferta
	);

	@WSDLDocumentation("Ritorna l'elenco degli esiti collegati ad elenco operatori economici.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoEsitiOutType getElencoEsitiAffidamenti(
            @WebParam(name = "filtri", targetNamespace = "")
            EsitoTypeSearch filtri
    );

	@WSDLDocumentation("Restituisce le statistiche delle comunicazioni ricevute e archiviate, " + 
			           "eventualmente da leggere, e quelle inviate, per una data entit&agrave;.")
    public it.maggioli.eldasoft.sil.gare.ws.GetStatisticheComunicazioniPersonaliOutType getStatisticheComunicazioniPersonali(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "codice2", targetNamespace = "")
        java.lang.String codice2,
        @WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
        java.lang.String stazioneAppaltante
    );

	@WSDLDocumentation("Restituisce la lista degli articoli filtrando per i parametri di input.")
    public it.maggioli.eldasoft.sil.gare.ws.SearchArticoliOutType searchArticoli(
        @WebParam(name = "codiceCatalogo", targetNamespace = "")
        java.lang.String codiceCatalogo,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceCategoria", targetNamespace = "")
        java.lang.String codiceCategoria,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(name = "descrizione", targetNamespace = "")
        java.lang.String descrizione,
        @WebParam(name = "colore", targetNamespace = "")
        java.lang.String colore,
        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
        int indicePrimoRecord,
        @WebParam(name = "maxNumRecord", targetNamespace = "")
        int maxNumRecord
    );

	@WSDLDocumentation("Restituisce il tipo di partecipazione dell'impresa al bando di gara.")
    public it.maggioli.eldasoft.sil.gare.ws.TipoPartecipazioneImpresaOutType getTipoPartecipazioneImpresa(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "progOfferta", targetNamespace = "")
        java.lang.String progOfferta
    );

	@WSDLDocumentation("Restituisce il dettaglio di una comunicazione inviata da un utente.")
    public it.maggioli.eldasoft.sil.gare.ws.ComunicazionePersonaleOutType getComunicazionePersonaleInviata(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "idComunicazione", targetNamespace = "")
        long idComunicazione,
        @WebParam(name = "idprg", targetNamespace = "")
        String idprg
    );

	@WSDLDocumentation("Ritorna il numero massimo di decimali utilizzabili per esprimere la " +
					   "percentuale di ribasso o aumento in un'offerta economica.")
    public it.maggioli.eldasoft.sil.gare.ws.RisultatoNumericoOutType getNumDecimaliRibasso();

	@WSDLDocumentation("Restituisce il dettaglio di una gara a partire da un suo lotto.")
    public it.maggioli.eldasoft.sil.gare.ws.DettaglioGaraOutType getDettaglioGaraFromLotto(
        @WebParam(name = "codiceLotto", targetNamespace = "")
        java.lang.String codiceLotto
    );

	@WSDLDocumentation("")	
    public java.lang.String getElencoUnitaMisura();

	@WSDLDocumentation("Restituisce la lista dei bandi abilitati all'inserimento di richieste di " +
	                   "invio documentazione per la comprova dei requisiti per l'impresa in input")
	public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType getElencoBandiPerRichiesteCheckDocumentazione(
            @WebParam(name = "filtri", targetNamespace = "")
            GaraTypeSearch filtri
	);

	@WSDLDocumentation("Restituisce l'elenco delle classificazioni dei lavori per l'iscrizione.")
    public java.lang.String getElencoClassificazioniLavoriPerIscrizione();

	@WSDLDocumentation("Restituisce i lotti di una gara abilitati per un'impresa per la richiesta di comprova requisiti")
    public it.maggioli.eldasoft.sil.gare.ws.LottiGaraOutType getLottiGaraPerRichiesteCheckDocumentazione(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

    /**
     * La risposta contiene l'xml di un oggetto del tipo DatiImpresaType definito in port-gare.xsd
     */
	@WSDLDocumentation("Estrae i dati dell'impresa da presentare all'atto dell'apertura di " + 
			           "una modifica anagrafica quando si estraggono dal backoffice")
    public it.maggioli.eldasoft.sil.gare.ws.GetDatiImpresaOutType getDatiImpresa(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "dataPartenzaCessati", targetNamespace = "")
        java.util.Date dataPartenzaCessati
    );

	@WSDLDocumentation("Restituisce l'elenco delle classificazioni dei servizi.")    
	public java.lang.String getElencoClassificazioniServizi();

	@WSDLDocumentation("Verifica se un'impresa &egrave; gi&agrave; registrata nel backoffice.")
    public it.maggioli.eldasoft.sil.gare.ws.EsitoOutType isImpresaRegistrata(
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        java.lang.String codiceFiscale,
        @WebParam(name = "partitaIva", targetNamespace = "")
        java.lang.String partitaIva,
        @WebParam(name = "isGruppoIva", targetNamespace = "")
        boolean isGruppoIva
    );

	@WSDLDocumentation("Restituisce lo username di un'impresa gi&agrave; registrata nel backoffice.")
	public it.maggioli.eldasoft.sil.gare.ws.RisultatoStringaOutType getImpresaRegistrata(
			@WebParam(name = "codiceFiscale", targetNamespace = "")
	        java.lang.String codiceFiscale,
	        @WebParam(name = "partitaIva", targetNamespace = "")
	        java.lang.String partitaIva,
	        @WebParam(name = "email", targetNamespace = "")
	        java.lang.String email,
	        @WebParam(name = "pec", targetNamespace = "")
	        java.lang.String pec
	);
		
	@WSDLDocumentation("Verifica se una gara prevede la busta per l'offerta tecnica " + 
			           "(perch&egrave; di tipo offerta economicamente pi&ugrave; vantaggiosa oppure " + 
			           "perch&egrave; gestita da configurazione della gara stessa).")
    public it.maggioli.eldasoft.sil.gare.ws.EsitoOutType isGaraConOffertaTecnica(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Restituisce i lotti di una gara a partire dalla sua chiave")
    public it.maggioli.eldasoft.sil.gare.ws.LottiGaraOutType getLottiGara(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Restituisce i lotti di un esito a partire dalla sua chiave.")
    public it.maggioli.eldasoft.sil.gare.ws.LottiEsitoOutType getLottiEsito(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Fornisce il prezzo migliore offerto per un determinato articolo " +
					   "considerando tutti i prodotti inseriti in catalogo.")
    public it.maggioli.eldasoft.sil.gare.ws.RisultatoDecimaleOutType getPrezzoMiglioreArticolo(
        @WebParam(name = "idArticolo", targetNamespace = "")
        long idArticolo
    );

	@WSDLDocumentation("Restituisce l'elenco dei tipi di appalto.")
    public java.lang.String getElencoTipiAppalto();

	@WSDLDocumentation("Estrae la lista eventuali delle voci aggiuntive da dettagliare per " + 
			           "ogni lavorazione e fornitura di un'offerta telematica.")
    public it.maggioli.eldasoft.sil.gare.ws.GetAttributiAggiuntiviOffertaOutType getAttributiAggiuntiviOfferta(
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice
    );

	@WSDLDocumentation("Restituisce le comunicazioni ricevute (cio&egrave; entro gli ultimi " +
				       "90 giorni) da un utente per una gara a lotti.")
    public it.maggioli.eldasoft.sil.gare.ws.ComunicazioniPersonaliOutType getComunicazioniPersonaliRicevuteGaraLotti(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
        @WebParam(name = "soccorsoIstruttorio", targetNamespace = "")
		java.lang.Boolean soccorsoIstruttorio,
		@WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
        int indicePrimoRecord,
        @WebParam(name = "maxNumRecord", targetNamespace = "")
        int maxNumRecord,
        @WebParam(name = "stazioneAppaltante")
        java.lang.String stazioneAppaltante
    );
	
	@WSDLDocumentation("Restituisce la lista dei contratti filtrando per i parametri di input.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoContrattiOutType searchContratti(
        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
        java.lang.String stazioneAppaltante,
        @WebParam(name = "oggetto", targetNamespace = "")
        java.lang.String oggetto,
        @WebParam(name = "cig", targetNamespace = "")
        java.lang.String cig,
        @WebParam(name = "stato", targetNamespace = "")
        java.lang.String stato,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

	@WSDLDocumentation("Restituisce l'elenco dei tipi impresa dei libero professionista.")
    public java.lang.String getElencoTipiImpresaLiberoProfessionista();

	@WSDLDocumentation("Restituisce l'elenco dei tipi impresa dei libero professionista.")
    public java.lang.String getElencoTipiImpresaSociale();
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di avviso.")
    public java.lang.String getElencoTipiAvviso();

	@WSDLDocumentation("Restituisce il dettaglio di un esito a partire dalla sua chiave.")
    public it.maggioli.eldasoft.sil.gare.ws.DettaglioEsitoOutType getDettaglioEsito(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara
    );

	@WSDLDocumentation("Restituisce la configurazione del check della partita iva facoltativa per un libero professionista.")
    public it.maggioli.eldasoft.sil.gare.ws.GetCfgCheckPIFacoltativaOutType getCfgCheckPIFacoltativaLiberoProfessionista();

	@WSDLDocumentation("Restituisce la configurazione del check della partita iva facoltativa per una impresa sociale.")
    public it.maggioli.eldasoft.sil.gare.ws.GetCfgCheckPIFacoltativaOutType getCfgCheckPIFacoltativaImpresaSociale();

	@WSDLDocumentation("Restituisce l'elenco dei tipi di procedura.")
    public java.lang.String getElencoTipiProcedura();

	@WSDLDocumentation("Restituisce il dettaglio di un catalogo a partire dalla sua chiave.")    
	public it.maggioli.eldasoft.sil.gare.ws.DettaglioBandoIscrizioneOutType getDettaglioCatalogo(
        @WebParam(name = "codiceCatalogo", targetNamespace = "")
        java.lang.String codiceCatalogo
    );

	@WSDLDocumentation("Ritorna l'elenco delle mandanti della RTI relativa alla procedura ed alla mandataria in input.")
    public it.maggioli.eldasoft.sil.gare.ws.GetMandantiRTIOutType getMandantiRTI(
        @WebParam(name = "codiceProcedura", targetNamespace = "")
        java.lang.String codiceProcedura,
        @WebParam(name = "tokenMandataria", targetNamespace = "")
        java.lang.String tokenMandataria,
        @WebParam(name = "progOfferta", targetNamespace = "")
        java.lang.String progOfferta
    );

	@WSDLDocumentation("Estrae il dettaglio di un prodotto.")
    public it.maggioli.eldasoft.sil.gare.ws.GetProdottoOutType getProdotto(
        @WebParam(name = "id", targetNamespace = "")
        long id
    );

	//  18/11/2016 IL METODO NON E' PIU' UTILIZZATO	
	//	  @WSDLDocumentation("")
	//    public it.maggioli.eldasoft.sil.gare.ws.ElencoBandiOutType getElencoBandiPerRichiesteOfferta(
	//        @WebParam(name = "tokenRichiedente", targetNamespace = "")
	//        java.lang.String tokenRichiedente
	//    );

	@WSDLDocumentation("Ritorna l'elenco di invii effettuati dall'utente in input su una " + 
					   "determinata procedura (elenco, catalogo), filtrando per tipologia di comunicazione.")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoInviiOutType getElencoInvii(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "codice", targetNamespace = "")
        java.lang.String codice,
        @WebParam(name = "tipiComunicazione", targetNamespace = "")
        java.util.List<java.lang.String> tipiComunicazione
    );

	@WSDLDocumentation("Restituisce il dettaglio di una comunicazione ricevuta da un utente.")
    public it.maggioli.eldasoft.sil.gare.ws.ComunicazionePersonaleOutType getComunicazionePersonaleRicevuta(
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente,
        @WebParam(name = "idComunicazione", targetNamespace = "")
        long idComunicazione,
        @WebParam(name = "idDestinatario", targetNamespace = "")
        long idDestinatario,
        @WebParam(name = "idprg", targetNamespace = "")
        String idprg
    );

	@WSDLDocumentation("Restituisce la lista degli avvisi di gara filtrando per i parametri di input")
    public it.maggioli.eldasoft.sil.gare.ws.ElencoAvvisiOutType searchAvvisi(
        @WebParam(name = "filtri", targetNamespace = "")
        AvvisiTypeSearch filtri
    );

	@WSDLDocumentation("Restituisce la lista delle categorie/prestazioni associate al bando d'iscrizione.")
    public it.maggioli.eldasoft.sil.gare.ws.CategorieBandoIscrizioneOutType getCategorieBandoIscrizione(
        @WebParam(name = "codiceBandoIscrizione", targetNamespace = "")
        java.lang.String codiceBandoIscrizione,
        @WebParam(name = "filtroCategorie", targetNamespace = "")
        java.lang.String filtroCategorie
    );

	@WSDLDocumentation("Restituisce i lotti di una gara non conclusi a partire dalla sua chiave, per la domanda di partecipazione.")
    public it.maggioli.eldasoft.sil.gare.ws.LottiGaraOutType getLottiGaraPerDomandePartecipazione(
        @WebParam(name = "codiceGara", targetNamespace = "")
        java.lang.String codiceGara,
		@WebParam(name = "progOfferta", targetNamespace = "")
		java.lang.String progOfferta
	);

	@WSDLDocumentation("Restituisce le comunicazioni ricevute (cio&egrave; entro gli ultimi 90 " +
	   				   "giorni) da un utente per una eventuale entit&agrave;.")
	public it.maggioli.eldasoft.sil.gare.ws.ComunicazioniPersonaliOutType getComunicazioniPersonaliRicevute(
		@WebParam(name = "tokenRichiedente", targetNamespace = "")
		java.lang.String tokenRichiedente,
		@WebParam(name = "codice", targetNamespace = "")
		java.lang.String codice,
		@WebParam(name = "codice2", targetNamespace = "")
		java.lang.String codice2,
		@WebParam(name = "soccorsoIstruttorio", targetNamespace = "")
		java.lang.Boolean soccorsoIstruttorio,
		@WebParam(name = "entita", targetNamespace = "")
        java.lang.String entita,
		@WebParam(name = "indicePrimoRecord", targetNamespace = "")
		int indicePrimoRecord,
		@WebParam(name = "maxNumRecord", targetNamespace = "")
		int maxNumRecord,
		@WebParam(name = "stazioneAppaltante", targetNamespace = "")
		java.lang.String stazioneAppaltante
	);
	
	@WSDLDocumentation("Ritorna l'elenco dei bandi di gara scaduti.")
	public ElencoBandiOutType getElencoBandiScaduti(
            @WebParam(name = "filtri", targetNamespace = "")
            GaraTypeSearch filtri
	);
	
	@WSDLDocumentation("Ritorna l'elenco dei bandi di gara scaduti per gare privatistiche.")
	public ElencoBandiOutType getElencoBandiScadutiPrivatistiche(
            @WebParam(name = "filtri", targetNamespace = "")
            GaraTypeSearch filtri
	);

	@WSDLDocumentation("Ritorna l'elenco della documentazione dell'asta.")
    public GetDocumentiInvitoAstaLottoOutType getDocumentiInvitoAstaLotto(
    		@WebParam(name = "codiceGara", targetNamespace = "") 
    		java.lang.String codiceGara,
            @WebParam(name = "codiceLotto", targetNamespace = "")
            java.lang.String codiceLotto
    );

	@WSDLDocumentation("Restituisce TRUE se una ditta è invitata e ammessa ad un'asta elettronica.")
    public java.lang.Boolean isInvitataAsta(
    		@WebParam(name = "codiceGara", targetNamespace = "") 
    		java.lang.String codiceGara,
            @WebParam(name = "username", targetNamespace = "")
            java.lang.String username
    );
	
	@WSDLDocumentation("Restituisce l'id della comunicazione di aggiornamento iscrizione posticipata.")
	public CheckAggiornamentoIscrizionePosticipataOutType checkAggiornamentoIscrizionePosticipata(
			@WebParam(name = "tokenRichiedente")
    	    String tokenRichiedente, 
    	    @WebParam(name = "codiceGara", targetNamespace = "")
    	    String codiceGara
	);

	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara per i soccorsi istruttori.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraSoccorsiElencoOperatori(
			@WebParam(name = "codiceGara", targetNamespace = "")
			String codiceGara,
			@WebParam(name = "codiceLotto", targetNamespace = "")
			String codiceLotto,
			@WebParam(name = "fase", targetNamespace = "")
			String fase,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);
	
	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara per la busta amministrativa.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraDocAmmElencoOperatori(
			@WebParam(name = "codiceGara", targetNamespace = "")
			String codiceGara,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);
	
	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara per la busta tecnica.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraValTecElencoOperatori(
			@WebParam(name = "codice", targetNamespace = "")
			String codice,
			@WebParam(name = "codiceLotto")
			String codiceLotto,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);

	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara a lotti per la busta tecnica.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraValTecElencoOperatoriLotto(
			@WebParam(name = "codice", targetNamespace = "")
			String codice,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);

	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara per la busta economica.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraOffEcoElencoOperatori(
			@WebParam(name = "codice", targetNamespace = "")
			String codice,
			@WebParam(name = "codiceLotto")
			String codiceLotto,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);
	
	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara a lotti per la busta economica.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraOffEcoElencoOperatoriLotto(
			@WebParam(name = "codice", targetNamespace = "")
			String codice,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);
	
	@WSDLDocumentation("Restituisce l'elenco degli operatori per l'espletamento di gara per la graduatoria.")
	public GetEspletamentoGaraElencoOperatoriOutType getEspletamentoGaraGraduatoriaElencoOperatori(
			@WebParam(name = "codiceGara", targetNamespace = "")
			String codiceGara,
			@WebParam(name = "tokenRichiedente")
			String tokenRichiedente
	);

	@WSDLDocumentation("Restituisce la fase di una gara.")
	public RisultatoNumericoOutType getFaseGara(
			@WebParam(name = "codice")
			String codice
	);

	@WSDLDocumentation("Restituisce le comunicazioni pubbliche degli ultimi 60 gg.")
    public it.maggioli.eldasoft.sil.gare.ws.ComunicazioniPersonaliOutType getNews(
    		@WebParam(name = "indicePrimoRecord", targetNamespace = "")
    		int indicePrimoRecord,
    		@WebParam(name = "maxNumRecord", targetNamespace = "")
    		int maxNumRecord,
    		@WebParam(name = "stazioneAppaltante", targetNamespace = "")
    		java.lang.String stazioneAppaltante
    );

//	@WSDLDocumentation("Restituisce l'elenco dei soggetti aderenti ad una gara.")
//	public it.maggioli.eldasoft.sil.gare.ws.SoggettiAderentiOutType getSoggettiAderenti(
//			@WebParam(name = "codiceGara", targetNamespace = "")
//			String codiceGara
//	);

	@WSDLDocumentation("Restituisce l'elenco degli operatori abilitati a un elenco.")
	public it.maggioli.eldasoft.sil.gare.ws.OperatoriIscrittiOutType getOperatoriIscritti(
			@WebParam(name = "codiceGara", targetNamespace = "")
			String codiceGara
	);

	@WSDLDocumentation("Restituisce l'elenco delle categorie relative agli operatori abilitati a un elenco.")
	public it.maggioli.eldasoft.sil.gare.ws.CategorieOperatoriIscrittiOutType getElencoCategorieOperatoriIscritti(
			@WebParam(name = "codiceGara")
			String codiceGara
	);

	@WSDLDocumentation("Restituisce l'elenco delle sezioni di iscrizione della whitelist antimafia.")
	public String getElencoSezioniIscrizioneWhitelistAntimafia();
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di rating legale.")
	public String getElencoRatingLegale();
	
	@WSDLDocumentation("Restituisce l'elenco delle classi di dimensione di un dipendente.")
	public String getElencoClassificazioneDimensioniDipendente();
	
	@WSDLDocumentation("Restituisce l'elenco dei settori di attività economica di un'impresa.")
	public String getElencoSettoriAttivitaEconomica();

	@WSDLDocumentation("Restituisce l'elenco degli altri soggetti.")
	public String getElencoAltriSoggetti();
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di raggruppamento delle imprese.")
	public String getTipiRaggruppamento();
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di regime fiscale delle imprese.")
	public String getTipiRegimeFiscale();
	
	@WSDLDocumentation("Restituisce l'elenco delle nazioni.")
	public String getNazioni();
	
	@WSDLDocumentation("Restituisce il cig o la lista dei cig per una procedura di gara.")
	public it.maggioli.eldasoft.sil.gare.ws.RisultatoStringaOutType getCigBando(@WebParam(name = "codiceGara") String codiceGara);	
	
	@WSDLDocumentation("Verifica l'esistenza di documenti senza contenuto per una procedura di gara.")
	public it.maggioli.eldasoft.sil.gare.ws.CheckDocumentiNulliOutType checkDocumentiNulli(String codiceGara, String username, String tipoBusta);

	@WSDLDocumentation("Verifica le differenze tra la dimensioni degli allegate originali e le dimensioni nel db per una procedura di gara.")
	public it.maggioli.eldasoft.sil.gare.ws.CheckDimensioneDocumentiOutType checkDimensioneDocumenti(String codiceGara, String username, String tipoBusta);

	@WSDLDocumentation("Restituisce l'elenco delle delibere a contrarre.")
	public DelibereOutType getDelibere(
			@WebParam(name = "annoInizio", targetNamespace = "")
	        java.lang.Integer annoInizio,
	        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
	        java.lang.String stazioneAppaltante,
	        @WebParam(name = "oggetto", targetNamespace = "")
	        java.lang.String oggetto,
	        @WebParam(name = "tipoAppalto", targetNamespace = "")
	        java.lang.String tipoAppalto,
	        @WebParam(name = "cig", targetNamespace = "")
	        java.lang.String cig,
	        @WebParam(name = "dataPubblicazioneDa", targetNamespace = "")
            java.util.Date dataPubblicazioneDa,
            @WebParam(name = "dataPubblicazioneA", targetNamespace = "")
            java.util.Date dataPubblicazioneA,
            @WebParam(name = "sommaUrgenza", targetNamespace = "")
	        java.lang.Boolean sommaUrgenza,
	        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
	        int indicePrimoRecord,
	        @WebParam(name = "maxNumRecord", targetNamespace = "")
	        int maxNumRecord
	);

	@WSDLDocumentation("Restituisce l'elenco delle gare di somma urgenza.")
	public SommaUrgenzaOutType getElencoSommaUrgenza(
	        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
	        java.lang.String stazioneAppaltante,
	        @WebParam(name = "oggetto", targetNamespace = "")
	        java.lang.String oggetto,
	        @WebParam(name = "tipoAppalto", targetNamespace = "")
	        java.lang.String tipoAppalto,
	        @WebParam(name = "cig", targetNamespace = "")
	        java.lang.String cig,
	        @WebParam(name = "dataPubblicazioneDa", targetNamespace = "")
            java.util.Date dataPubblicazioneDa,
            @WebParam(name = "dataPubblicazioneA", targetNamespace = "")
            java.util.Date dataPubblicazioneA,
	        @WebParam(name = "indicePrimoRecord", targetNamespace = "")
	        int indicePrimoRecord,
	        @WebParam(name = "maxNumRecord", targetNamespace = "")
	        int maxNumRecord
	);
	
	
	@WSDLDocumentation("Restituisce i parametri di configurazione per la protocollazione WSDM.")
	public WSDMConfigOutType getWSDMConfig(
	        @WebParam(name = "stazioneAppaltante", targetNamespace = "")
	        java.lang.String stazioneAppaltante
	);
	
	@WSDLDocumentation("Restituisce il codice impresa di un dato username.")
	public String getIdImpresa(
			@WebParam(name = "username", targetNamespace = "")
			java.lang.String username
	);		

	@WSDLDocumentation("Restituisce l'elenco degli inviti di gara.")
	public InvitiGaraOutType getElencoInvitiGara(
			@WebParam(name = "username", targetNamespace = "")
			String username, 
			@WebParam(name = "codice", targetNamespace = "")
			String codice 
	);

	@WSDLDocumentation("Restituisce il numero di ordine dell'invio di una ditta per una dato bando")
	public RisultatoNumericoOutType getNumeroOrdineInvito(
			@WebParam(name = "username", targetNamespace = "")
			String username, 
			@WebParam(name = "codice", targetNamespace = "")
			String codice 
	);

	@WSDLDocumentation("Restituisce i questionari associati alle buste di una gara.")
	public QuestionarioOutType getQuestionari(
			@WebParam(name = "codice", targetNamespace = "")
			String codice,
			@WebParam(name = "tipologia", targetNamespace = "")
			String tipologia,
			@WebParam(name = "busta", targetNamespace = "")
			String busta
	);

	@WSDLDocumentation("Restituisce l'elenco dei parametri associati a un questionario.")
	public ParametriQuestionarioOutType getParametriQuestionario();
	
	@WSDLDocumentation("Restituisce l'elenco delle fasi della stipula.")
	public String getElencoFasiStipula();
	
	@WSDLDocumentation("Restituisce l'elenco degli stati della stipula.")
	public String getElencoStatiStipula();
	
	@WSDLDocumentation("Restituisce l'elenco dei tipi di prodotto di un elenco operatore.")
	public String getTipologiaProdotto();

	@WSDLDocumentation("Restituisce la configurazione del check della gruppo iva.")
	public GetCfgCheckParametroOutType getCfgCheckGruppoIvaAbilitato();

    @WSDLDocumentation("Lista dei tipi di ammissione per la procedura in espletamento di gara")
	public String getTipiAmmissioneProcedura();

    @WSDLDocumentation("Informazioni Vendor Rating")
    public GetVendorRatingOutType getVendorRating(@WebParam(name = "tokenRichiedente", targetNamespace = "")
                                                String tokenRichiedente,
                                            @WebParam(name = "data", targetNamespace = "")
                                                java.util.Date data);

}
